name: 'AutoCheck JavaScript tests by Testomatio'
description: 'Check new or removed tests on each pull requests. List all tests before running them'
branding:
  icon: check-circle
  color: blue
inputs:
  framework: # id of input
    description: 'Test framework to be used. Supported: mocha, codeceptjs'
    required: true
  tests: # id of input
    description: 'Glob pattern to match tests in a project, example: tests/**_test.js'
    required: true
  token:
    description: GitHub token to post comment with summary to current pull request
    required: false
  has-tests-label:
    description: Add 'has tests' label to PR when it contains new tests
    required: false
  no-tests-label:
    description: Add 'no tests' label to PR when it doesn't contain new tests
    required: false
  comment-on-empty:
    description: 'Post a comment to PR when no tests added. Can be either boolean (for neutral message) or a custom message within a comment'
    required: false
  close-on-empty:
    description: 'Close PR when no tests added. Use with comment-on-empty to clarify this action'
    required: false
  comment-on-skipped:
    description: 'Post a comment to PR when tests were skipped. Can be either boolean (for neutral message) or a custom message within a comment'
    required: false
  close-on-skipped:
    description: 'Close PR when no tests added. Use with comment-on-skipped to clarify this action'
    required: false
  enable-documentation:
    description: 'If set true test document will be created in wiki'
    required: false
  wiki-doc-name:
    description: 'Name of the wiki document. By default it will use "Test Document"'
    required: false
  github-pat:
    description: 'Github Private access token to create document in wiki'
    required: false
  documentation-branch:
    description: 'Branch to create document on push uses default branch if empty'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
